name: Deploy website

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-slim
    permissions:
      id-token: write # to use actions/deploy-pages
      pages: write # to push to a github pages site
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: fetch data and build html
        run: cargo xtask oneshot

      - name: copy to public
        run: |
          mkdir public
          mv index.html public/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: web/dist/public

      - id: deployment
        uses: actions/deploy-pages@v4
